### ISSUE TITLE
[BUG] <Fingerprint Search on MDT not working>

### ISSUE THREAD

**Issue by M1ngh** [ParadoxGamingRP/bugs-and-suggestions#942] opened 2022-11-24 23:10 UTC
### Your Discord Name
Minghee#0876
### A clear and concise description of what the bug is

When you try to search by fingerprints on Profiles section or on the add criminal section in arrest/reports, doenst show the criminal.

### Steps to Reproduce the Bug

1. get fingerprint from scan
2. open MDT and go on profiles
3. paste fingerpirnt or writte it manually
4. no profile is showed

### Expected Behavior

1. get fingerprint from scan
2. open MDT and go on profiles
3. paste fingerpirnt or writte it manually
4. shows suspect profile

### Screenshots/Videos

https://user-images.githubusercontent.com/107653844/203872937-777e0e38-4e7f-450e-9891-43598b71c635.mp4

### Log File

[CitizenFX_log_2022-11-24T213730.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10087638/CitizenFX_log_2022-11-24T213730.log)

**Comment by xXJamieXx** [comment] 2022-11-26 23:33
Duplicate of #930

**Closed by xXJamieXx** 2022-11-26 23:33 UTC
Labels: Bug
