### ISSUE TITLE
[BUG] ATM Robberies

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#1981] opened 2023-12-07 08:04 UTC
### Your Discord Name

bdz

### A clear and concise description of what the bug is

Try to use a USB on an atm when cops are around and the USB will not work. The USB will not turn into an empty USB after use and will not give any money rolls or PDX sticks.

### Steps to Reproduce the Bug

1. Use USB stick
2. Receive nothing
3. USB does not turn into an Empty USB
4. Very sad

### Expected Behavior

When using the USB, uses up the USB and turns it into an empty USB. Receive money rolls and PDX sticks

### Screenshots/Videos

n/a

**Comment by xXJamieXx** [comment] 2023-12-07 18:51
Duplicate of #1977

**Closed by xXJamieXx** 2023-12-07 18:51 UTC
Labels: type: Bug
