### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by Islaq** [ParadoxGamingRP/bugs-and-suggestions#2090] opened 2024-02-07 04:33 UTC
### Your Discord Name

dazedbby

### A clear and concise description of what the bug is

When on cop when pursuing or looking at map officers blips do not show up, near on the side where you can see different place and blips.

### Steps to Reproduce the Bug

1. hit esc
2. see or be able to follow officers blip

### Expected Behavior

It is expected to be able to see officers call signs/blips on the map when you hit esc.

### Screenshots/Videos

![noblips](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/118240669/6bbb6f69-1e5f-43fd-b10c-53492090a800)

**Comment by Kromlec** [comment] 2024-02-07 04:39
Duplicate of #2088

**Closed by Kromlec** 2024-02-07 04:39 UTC
Labels: type: Bug
