### ISSUE TITLE
[ENHANCEMENT] Screen Shake

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#2078] opened 2024-01-31 20:27 UTC
**Your Discord Name**
davefromsunderland

**Describe the annoyance**
screen shakes like help when driving and walking even with the "disable third person camera shake" option selected on the fivem main page. 

**To Reproduce**
1. Drive/Run
2. Screen Shakes and makes it hard to drive 

**Requested behavior**
For my screen not to shake

**Additional context**
This has never been an issue up until the restart that happened a few hours ago.

**Comment by Kromlec** [comment] 2024-01-31 20:28
Duplicate of #2077

**Closed by Kromlec** 2024-01-31 20:28 UTC
Labels: type: Enhancement
