### ISSUE TITLE
Jail [BUG] 

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#2309] opened 2024-06-01 22:28 UTC
### Your Discord Name

imtwobigdawg35#3143

### A clear and concise description of what the bug is

Immediately reduce your jail sentence.

### Steps to Reproduce the Bug

1. get sent to jail
2. once in jail soft nap or /logout
3. fly back in on same character
4. have no jail time

### Expected Behavior

to have the same amount of jail time

### Screenshots/Videos

N/A

### Log File

[jail time.txt](https://github.com/user-attachments/files/15523566/jail.time.txt)

**Comment by CorFinn** [comment] 2024-06-01 23:15
Duplicate of #2294.

**Closed by CorFinn** 2024-06-01 23:15 UTC
Labels: type: Bug, state: Duplicate
