### ISSUE TITLE
[BUG] Big house robbery

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2479] opened 2024-06-26 17:38 UTC
### Your Discord Name

ssara

### A clear and concise description of what the bug is

I tried ot get a big house to rob. Went in and searched the first part - fine.
Next one - already searched.
Next one - already searched.
The rest of them - already searched
I did not search them in fact, I was only able to open the first one.

### Steps to Reproduce the Bug

Get a big house from the dude
Search in the house
Get lucky once
Cant search the others cause it will say that already searched.

### Expected Behavior

Be able to be a bad girl

### Screenshots/Videos

N/A

### Log File

[robbinghouse.txt](https://github.com/user-attachments/files/15993018/robbinghouse.txt)

**Comment by emeraldleo1982** [comment] 2024-06-30 07:20
Can confirm this is still happening. First house went fine, 2nd house of the night was all "Already Searched".

https://medal.tv/games/gta-v/clips/iaIqfsiD8H4QEN3P4/d1337NNtpKF0?invite=cr-MSxTMkksMTUzNDM4NTc5LA

No relevant log output.

**Comment by xXJamieXx** [comment] 2024-07-13 16:19
Duplicate of #2400

**Closed by xXJamieXx** 2024-07-13 16:19 UTC
Labels: team: Scripting, type: Bug
