### ISSUE TITLE
[BUG] not able to put attachment back on gun

### ISSUE THREAD

**Issue by Ball33er2** [ParadoxGamingRP/bugs-and-suggestions#1508] opened 2023-06-15 23:15 UTC
### Your Discord Name

Ball33er#9699

### A clear and concise description of what the bug is

When you move a tactical suppressor off of an ak, the tactical suppressor can not be put back on any gun.  I tried with an ak and a deagle and both gave me the error message saying "you must have a weapon in hand"

### Steps to Reproduce the Bug

1. Remove tactical suppressor from gun
2. try and put it back on a gun.
3. doesn't register the gun

### Expected Behavior

Should be able to put the suppressor back on your gun.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1epmEd-T6qRKo7/d1337yqQh50X?invite=cr-MSx1MXEsNzAwMDQ2Mzcs

**Comment by xXJamieXx** [comment] 2023-06-18 21:07
Duplicate of #1518

**Closed by xXJamieXx** 2023-06-18 21:07 UTC
Labels: team: Scripting, type: Bug, state: Duplicate
