### ISSUE TITLE
[BUG] Fire/Medical Repair  stations broken

### ISSUE THREAD

**Issue by Nalyd24** [ParadoxGamingRP/bugs-and-suggestions#2283] opened 2024-05-31 10:07 UTC
### Your Discord Name

Nalyd24

### A clear and concise description of what the bug is

When trying to use  the repair stations at fire/medical repair stations, you get the radial  menu option however  when you try to click it noting happens and radial menu closes without repairing the vehicle

### Steps to Reproduce the Bug

1. go to a Hospital or Fire station
2. try to repair a vehicle
3. open radial menu
4. find **_Repair Vehicle_** option
5. wonder why your vehicle isnt being repaired

### Expected Behavior

1. go to a Hospital or Fire station
2. try to repair a vehicle
3. open radial menu
4. find **_Repair Vehicle_** option
5. vehicle gets repaired

### Screenshots/Videos

https://r2.fivemanage.com/images/8FZts6VERCHe.png
https://r2.fivemanage.com/images/t70VWNNJXWJS.png

**Comment by xXJamieXx** [comment] 2024-06-02 16:14
Duplicate of #2274

**Closed by xXJamieXx** 2024-06-02 16:14 UTC
Labels: team: Scripting, type: Bug, state: Duplicate
