### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SushiiPlays** [ParadoxGamingRP/bugs-and-suggestions#633] opened 2022-08-05 15:01 UTC
### Your Discord Name

sushiiplays#0120

### A clear and concise description of what the bug is

Whenever I hit the K button to use the spray can it doesn't work. I've tried a house with a interior, outside a house with a interior, and around a house without interior. I tried turning the view distance and text size to max amount. I tried taking a nap but it doesn't fix it. I've heard of my friends also having the same issue.

### Steps to Reproduce the Bug

Use the K button for the spray can.

### Expected Behavior

I expected for my text to display as I place it and as I preview it. Instead it doesn't preview or display when hitting the K button. 

### Screenshots/Videos

![Screenshot 2022-08-05 103550](https://user-images.githubusercontent.com/110682189/183104244-ec614aa8-3f0c-4668-b09d-62de3221eaa0.png)
![Screenshot 2022-08-05 103816](https://user-images.githubusercontent.com/110682189/183104253-761b19d8-4f85-4fd6-b326-19ea288758bb.png)
![Screenshot 2022-08-05 103832](https://user-images.githubusercontent.com/110682189/183104258-9fcc5138-880e-4325-a443-8159f7af9120.png)
![Screenshot 2022-08-05 104003](https://user-images.githubusercontent.com/110682189/183104263-a1fbb194-3ab4-43f4-a43b-33809b137770.png)

### Log File

[CitizenFX_log_2022-08-05T144705.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9269752/CitizenFX_log_2022-08-05T144705.log)
[CitizenFX_log_2022-08-05T144731.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9269753/CitizenFX_log_2022-08-05T144731.log)

**Comment by xXJamieXx** [comment] 2022-08-05 15:23
Duplicate of #573

**Closed by xXJamieXx** 2022-08-05 15:23 UTC
