### ISSUE TITLE
[BUG] fishing cancelling after every auto-recast+ excess loot not dropping on the ground if it exceeds limit

### ISSUE THREAD

**Issue by mjb328** [ParadoxGamingRP/bugs-and-suggestions#686] opened 2022-08-25 16:05 UTC
### Your Discord Name

MJB328#5303

### A clear and concise description of what the bug is

When fishing occasionally it auto recast, but for the 3-4 days atleast when I auto-recast it cancels on it own. Plus any item caught that exceed inv weight limit arent dropping to the ground for pick up.

### Steps to Reproduce the Bug

1. full you inv near capacity to save time
2. fish until it auto recast and can see it cancel out on its own.
3. Afterwards fish till you reach capacity and excess loot doesn't drop to the ground.

### Expected Behavior

For auto cast to not cancel on its own, and for excess loot to drop to the ground if it exceeds inv weight limit

### Screenshots/Videos

![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 8_25_2022 12_05_31 PM](https://user-images.githubusercontent.com/103229041/186714852-913e2460-8bc8-438c-843b-55636dc76da8.png)

### Log File

[Fishingbuggedlogs.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9426430/Fishingbuggedlogs.txt)

**Comment by xXJamieXx** [comment] 2022-08-27 16:24
1. This is two bugs that should have been reported in separate issues.
2. The full inventory bug is a duplicate of #685 and is fixed next restart
3. There is no auto recast, you have to use the item after each time you catch a fish.

**Closed by xXJamieXx** 2022-08-27 16:24 UTC
