### ISSUE TITLE
[BUG] LEO vehicles not saving extras

### ISSUE THREAD

**Issue by RizzleMyNizzle** [ParadoxGamingRP/bugs-and-suggestions#910] opened 2022-11-13 19:45 UTC
### Your Discord Name

RizzleMyNizzle#8454

### A clear and concise description of what the bug is

The PD cars are not saving extras. When I go and put extras on cruiser it does not save. I think all the motorpool cars are having the same issue. Mine is a personal cruiser and every time I go on duty I have to go put the extras back on. 

### Steps to Reproduce the Bug

Go to bennys and add extras to cruiser
Repair vehicle
Store in garage
Take out of garage and extras are gone

### Expected Behavior

To keep extras on owned cruisers and motorpool vehicles

### Screenshots/Videos

https://i.imgur.com/SJ8Dh4I.jpeg

**Comment by CorFinn** [comment] 2022-11-13 19:52
Duplicate of #896
Issues are identical, just with different vehicle.

**Closed by CorFinn** 2022-11-13 19:52 UTC
Labels: Confirmed, Duplicate, Bug
