### ISSUE TITLE
[BUG] Edge case inv issues?

### ISSUE THREAD

**Issue by BennieBoi64** [ParadoxGamingRP/bugs-and-suggestions#763] opened 2022-09-15 00:59 UTC
### Your Discord Name

Bennyboi#8605

### A clear and concise description of what the bug is

I tried to place 46 rubber on to another stack of 26 I had in a mule, I placed the rubber on to the current stack and it added up perfectly to 72. I exit out of the mule and go to look back in it and I only see 26, my 46 rubber had disappeared. 

### Steps to Reproduce the Bug

Have a friend put rubber in the back of a mule.
Then you try and place more rubber onto that stack in the mule.
Go out and back into the mule and the more rubber that you tried to place onto the current stack in the mule should be gone.

### Expected Behavior

I expected that the rubber I tried to place on to the current stack of rubber inside the mule would stack up.

### Screenshots/Videos

I have no screenshots or recordings aside from the current 26 rubber that is now only in there.
![image](https://user-images.githubusercontent.com/113565315/190288745-ae8795f9-71ab-4466-af43-efa4a08ad801.png)

### Log File

[CitizenFX_log_2022-09-14T215740.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9570851/CitizenFX_log_2022-09-14T215740.log)

**Comment by xXJamieXx** [comment] 2022-10-04 13:50
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-10-04 13:50 UTC
Labels: Unable to Reproduce, Bug
