### ISSUE TITLE
[BUG] Moving Apartment wipes stash.

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1043] opened 2023-01-25 07:26 UTC
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Moving apartments gives clean new stash.

### Steps to Reproduce the Bug

1: Move Apartment locations for $500.
2: Check Stash (Is empty)
3: Move apartments back to original location.
4: Check stash (Is full again)

### Expected Behavior

I'm not sure. I mean it makes logical sense to have a different stash in each apartment location, but it also makes game balance sense to not have access to unique stashes around the city with a $500 access fee.

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment] 2023-01-25 16:44
Duplicate of #1031

**Closed by xXJamieXx** 2023-01-25 16:44 UTC
Labels: Bug
