### ISSUE TITLE
[BUG] Armor respawn

### ISSUE THREAD

**Issue by Dat-Ascot** [ParadoxGamingRP/bugs-and-suggestions#619] opened 2022-07-31 00:55 UTC
### Your Discord Name

Propster#2897

### A clear and concise description of what the bug is

so i noticed the other day that my armor would replenish if it was damaged a bit on a tsunami/nap. today i flew in this morning lost my armor entirely and was at 50%hp... fly back in after tsunami and i have 75% armor again

### Steps to Reproduce the Bug

Step 1: Apply armor
Step 2: Take damage to armor/ lose armor
Step3: Tsunami fixes armor/ replaces broken armor

### Expected Behavior

Make armor need to be repurchased and applied if damaged or broken

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment] 2022-08-04 09:44
Will be investigating this as its becoming a re-occurring issue. Will be having log files posted from testers here to determine the root cause and hopefully determine a fix.

**Comment by natashajoan** [comment] 2022-08-05 19:00
I tried with a pizza, had the 3/4 it gave, flew out, flew back in and no armour. ID was 125


[](url
[CitizenFX_log_2022-08-05T185034.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9271042/CitizenFX_log_2022-08-05T185034.log)
[CitizenFX_log_2022-08-05T185158.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9271043/CitizenFX_log_2022-08-05T185158.log)
)

**Comment by xXJamieXx** [comment] 2022-08-05 19:56
@Dat-Ascot what did you use to apply the armour? Was it pizza or something else?

**Comment by xXJamieXx** [comment] 2022-08-07 11:41
Going to mark this as fixed. Feel free to open a new issue if its still happening.

**Closed by xXJamieXx** 2022-08-07 11:41 UTC
Labels: Scripting
