### ISSUE TITLE
[ENHANCEMENT] Locals Stealing Weed Bags

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#647] opened 2022-08-11 07:39 UTC
### Your Discord Name

BDZ#0001

### A clear and concise description of what the bug is

When selling bags to locals, theres a chance for the locals to steal your bags. When you shoot or punch these locals you do not get the bags of weed back. 

### Steps to Reproduce the Bug

1.Start Selling Weed
2.Local steals weed bags
3. Cap the local
4. Dont get the bags back

### Expected Behavior

Should be able to get the bags of weed back.

### Screenshots/Videos

NONE

**Comment by SpiceF0x** [comment] 2022-08-11 11:25
Not a bug, might wanna recategorize as QOL Enhancement.

**Comment by ithegreatgatsby** [comment] 2022-08-16 23:03
Locals stealing from you have been disabled until it can be reworked. Closing for now feel free to make a QOL report on this later on

**Closed by ithegreatgatsby** 2022-08-16 23:03 UTC
Labels: Enhancement, Scripting
