### ISSUE TITLE
[BUG] Peds have caught the 75% health bug, needs a doctor.

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1369] opened 2023-04-18 15:43 UTC
### Your Discord Name

J_plink#1691

### A clear and concise description of what the bug is

Whenever Tin Man wakes up from a nap, no matter how long it is, he just never wakes up feeling more than 75% of himself. I would imagine this is a similar strain of the bug that was spreading amoung the women of the city. It would seem as though the bug has spread to the unique group of "Ped" characters in the city now as well. Tin Man is, a Man, but he is also a Ped, so its probably safe to assume this is happening to other Peds as well.

### Steps to Reproduce the Bug

1. Make sure your Ped character is well fed, watered, and healthed-up before you go to sleep. 
2. Wake up as your Ped Character
3. Notice you wake up only feeling 75% of yourself.
4. Be upset because I have to put on a band aid for a booboo I did in my sleep. 

### Expected Behavior

Be able to wake up at the same level of health I was at before I went to sleep. Not have to give a big corporation like LTD more money for Paw Patrol band-aids than I already do! 

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-04-18T152600.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11263648/CitizenFX_log_2023-04-18T152600.log)

**Comment by JnKTechstuff** [comment] 2023-04-18 15:56
Duplicate of https://github.com/ParadoxGamingRP/bugs-and-suggestions/issues/1366

**Closed by JnKTechstuff** 2023-04-18 15:56 UTC
Labels: type: Bug
