### ISSUE TITLE
Bikini tow Dispatch doesn't work

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#760] opened 2022-09-14 00:14 UTC
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

While clocked into Bikini Tow you are not able to open your dispatch panel, both big and small.

### Steps to Reproduce the Bug

Clock in to Bikini Tow
Attempt to open Dispatch panel

### Expected Behavior

Dispatch panel should open

### Screenshots/Videos

No pictures available.

### Log File

[Bikini Dispatch.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9561565/Bikini.Dispatch.txt)

**Comment by xXJamieXx** [comment] 2022-09-14 15:03
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-09-14 15:03 UTC
Labels: Unable to Reproduce, Scripting, Bug
