### ISSUE TITLE
[BUG] Its still furnitures glued to my floor..

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1415] opened 2023-05-10 17:02 UTC
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Still cant remove furnitures, so I'm re-opening this.

### Steps to Reproduce the Bug

Try to remove a already put down furniture
Dont get removed

### Expected Behavior

Be removed.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/18I7vgIK6CcPkV/d1337zeENSHf?invite=cr-MSxzRHYsNDU3NjU0MzAs

### Log File

[furnitures.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11444414/furnitures.txt)

**Comment by xXJamieXx** [comment] 2023-05-10 17:04
Duplicate of #841

**Closed by xXJamieXx** 2023-05-10 17:04 UTC
Labels: type: Bug
