### ISSUE TITLE
[BUG] Car Chopping Guy Missing

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1719] opened 2023-08-15 23:19 UTC
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Got the car for the chop, and led me to the area where the chop guy should be and they are not there to collect the parts.

### Steps to Reproduce the Bug

1. Get car chopping mission
2. Get that car in that area.
3. set location
4. go to location

### Expected Behavior

Guy there to let chop cars for parts.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/00257a76-9005-4d61-901f-7f9c79200c6d)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/5541471f-8d28-4a4a-8f6c-251a9717a146)

**Comment by Kromlec** [comment] 2023-08-21 17:43
Duplicate of 1697.

**Comment by xXJamieXx** [comment] 2023-08-22 20:10
Duplicate of #1697

**Closed by xXJamieXx** 2023-08-22 20:10 UTC
Labels: type: Bug
