### ISSUE TITLE
[BUG] Vehicle modifications reset

### ISSUE THREAD

**Issue by TheGraveyardShift** [ParadoxGamingRP/bugs-and-suggestions#725] opened 2022-09-03 17:05 UTC
### Your Discord Name

TheGraveyardShift#6865

### A clear and concise description of what the bug is

 This has only happened twice and both times to my Cheval Picador. Whenever i seem to have this car out and end up going down and having to go to Pillbox, it resets everything. Engine tunings, liveries, extras, tires, etc. The only things that are kept were the paint job and window tint.

### Steps to Reproduce the Bug

1. Own a Cheval Picador
2. Go down and either airlift to Pillbox or have someone take you
3. Go back to the car and it should be reset.

### Expected Behavior

That the car stays the same whether I go down or not.

### Screenshots/Videos

![Screenshot (1941)](https://user-images.githubusercontent.com/104471236/188280977-83f81529-ba6d-440f-932b-63c5173142c2.png)
^^^ this is what my car looked like before

![yeerrrr](https://user-images.githubusercontent.com/104471236/188280994-d52658a8-052f-4a7d-ab9b-16cfc7b49210.jpg)
^^^ and this is what it looked like after going down

### Extra Notes (Optional)

This hasn't happened to any of my other vehicles that i know of. Maybe it has and I haven't noticed but.

### Log File

[CitizenFX_log_2022-09-03T041505.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9483036/CitizenFX_log_2022-09-03T041505.log)

[CitizenFX_log_2022-09-03T041538.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9483037/CitizenFX_log_2022-09-03T041538.log)

It happened between these to logs

**Comment by JnKTechstuff** [comment] 2022-09-03 17:38
I doubt this has anything to do with you going down.

**Comment by TheGraveyardShift** [comment] 2022-09-04 02:22
I dont know what else would cause it. Do you?

**Comment by TheGraveyardShift** [comment] 2022-09-04 06:43
Okay definitely not because of going down. I think its just this specific car model that doesn't hold customization

**Comment by xXJamieXx** [comment] 2022-09-11 23:07
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-09-11 23:07 UTC
Labels: Unable to Reproduce, Scripting, Bug
