### ISSUE TITLE
[BUG] Racing Harnesses 

### ISSUE THREAD

**Issue by o7JStreet** [ParadoxGamingRP/bugs-and-suggestions#727] opened 2022-09-04 16:44 UTC
### Your Discord Name

BayHarbourButcher#6820

### A clear and concise description of what the bug is

Racing Harnesses intend to snap when you go ahead and use them once, Once you have them in either your 1-5 hot pockets it intends to disappear after flexing said pocket immediately. 

### Steps to Reproduce the Bug

1. Buy a Racing Harness from Bikini Tow
2. Put Racing Harness into 1-5 hot buttons.
3. Flex that button with the harness in it.

### Expected Behavior

Racing Harnesses should be a multiple use thing, I estimate they should have upto 30-50 uses.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/zyg6EbqjrpZ3a/d13372IuvO8D?invite=cr-MSw1Z3IsMjM4MzMzNzYs

### Log File

[CitizenFX_log_2022-09-03T231553.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9485090/CitizenFX_log_2022-09-03T231553.log)

**Comment by JnKTechstuff** [comment] 2022-09-05 21:55
Can't reproduce this

**Comment by xXJamieXx** [comment] 2022-09-11 23:12
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-09-11 23:12 UTC
Labels: Unable to Reproduce, Bug
