### ISSUE TITLE
[ENHANCEMENT] repair at firestation

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#897] opened 2022-11-06 10:52 UTC
**Your Discord Name**
Ssara#7821 

**Describe the annoyance**
People within the EMS-department have been staging down at the fire station at postal 178. When they do so they forget to fix the ambulances after them, giving other people ambulances with red engines and repair costs for over 300. If there's a possibility to have a repair spot down at the fire station so there's no excuses to not repair it, that would be very helpful. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Pull out an ambo 
2. Stage at fire Station 
3. Forget to repair it. 

**Requested behavior**
We'd like a repair place down at the fire station, please. 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
Have a great day!

**Comment by xXJamieXx** [comment] 2022-11-10 19:58
duplicate of #891

**Closed by xXJamieXx** 2022-11-10 19:58 UTC
Labels: Enhancement, Scripting, - In Next Update
