### ISSUE TITLE
[BUG] Fishing Rod Says No Bait

### ISSUE THREAD

**Issue by FayeBlackheart** [ParadoxGamingRP/bugs-and-suggestions#1811] opened 2023-09-23 05:29 UTC
### Your Discord Name

Faye Blackheart

### A clear and concise description of what the bug is

I bought a brand new fishing rod and gold shiner bait, went out to the pier to fish, dragged some bait onto the fishing rod.  It loads the animation saying I'm loading bait onto the hook, the bait is deleted from my inventory, but then when I go to use my fishing rod, either by clicking "use" or by using the hotkey, it says I have no bait.  

### Steps to Reproduce the Bug

1.  Drag golden shiner bait onto fishing rod in your inventory.
2.  Wait as it animates loading the bait.
3.   The bait is showing as being removed from the inventory.
4.   "Use" the fishing rod, either with a hot key or by clicking use, and it says there is no bait and fails to pull out your fishing rod.

### Expected Behavior

Once bait is loaded, the fishing rod should go into my hands so I can fish.

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-09-23T045805.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12705667/CitizenFX_log_2023-09-23T045805.log)

**Comment by BlazinNut** [comment] 2023-09-23 07:55
Can Confirm

**Comment by Bac0nRamen** [comment] 2023-10-04 13:51
duplicate of #1801

**Closed by Bac0nRamen** 2023-10-04 13:51 UTC
Labels: state: Confirmed, type: Bug
