### ISSUE TITLE
[BUG] Farming Broken - produces 0 quantities/weights

### ISSUE THREAD

**Issue by FayeBlackheart** [ParadoxGamingRP/bugs-and-suggestions#862] opened 2022-10-26 07:42 UTC
### Your Discord Name

Faye Blackheart#7984

### A clear and concise description of what the bug is

Tried to farm a few of everything tonight, including all the seeds that are planted on farms, along with rubber seeds.  Watered them, fertilized them...they grew, then when at full growth I harvested them, to have them go into my inventory with quantities and weights listed as zero "0."   This was the case on everything that you grow (can't speak to weed, didn't try that)...but because the quantity was zero, I couldn't use it to feed livestock or sell it.   When I tried to give one of my "0" carrots to the pig, the animation played like I was feeding him, but then I got an error message saying "error removing food item."  I checked afterwards, and the pig did not show any effect from the carrot, so it didn't actually feed him.
Photos of what I harvested showing "0" are below, potatoes, corn, grain, and carrot, along with the error message after trying to feed the broken carrot to the pig.

### Steps to Reproduce the Bug

1.  Plants any seeds or plants
2.  Water/Fertilize (or don't)
3. Harvest at any time (I waited until full growth)
4. They will go into your inventory without quantities and won't work.

### Expected Behavior

I would expect quantities of plants I harvested so I can sell them or use them.

### Screenshots/Videos

![IMG_3501](https://user-images.githubusercontent.com/115768950/197964571-431b4546-4a44-4e09-9bcc-ef658282b40e.jpg)
![IMG_3503](https://user-images.githubusercontent.com/115768950/197964654-f7b01eaa-5e93-4b70-a7ae-30a55c7cd625.jpg)

### Log File

I can't find this, if you need this please contact me for additional help locating.

**Comment by JnKTechstuff** [comment] 2022-11-05 21:01
No one else has reported this issue and I know they have been farming

**Comment by xXJamieXx** [comment] 2022-11-10 18:54
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-11-10 18:54 UTC
Labels: Unable to Reproduce, Scripting, Bug
