### ISSUE TITLE
[BUG] Car livery wont be removed

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1271] opened 2023-03-15 13:41 UTC
### Your Discord Name

Rogue#5265

### A clear and concise description of what the bug is

So when ever I take out my Annis S-230 it spawns in with the old livery that I removed and no matter what I do its always there.
I also did put the car in the garage as soon as I changed it.

### Steps to Reproduce the Bug

Get rid of the Livery
Put car in any garage
Pull out car and then the car will have the livery

### Expected Behavior

Maybe the car being tested out in a test server? Or if anyone else has the same issues as me. 

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-03-15T132310.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10980407/CitizenFX_log_2023-03-15T132310.log)

**Comment by Kromlec** [comment] 2023-03-15 14:49
Duplicate of #1266

**Comment by ithegreatgatsby** [comment] 2023-03-26 15:54
closing due to being a duplicate of #1266

**Closed by ithegreatgatsby** 2023-03-26 15:54 UTC
Labels: type: Bug
