### ISSUE TITLE
[BUG] Liveries not saving again

### ISSUE THREAD

**Issue by iineedmyjuul** [ParadoxGamingRP/bugs-and-suggestions#1527] opened 2023-06-19 19:00 UTC
### Your Discord Name

pchimpinn

### A clear and concise description of what the bug is

Same issue as a few months ago, liveries are reapplying when pulling a car from a garage, even if there was no livery when it was parked. 

### Steps to Reproduce the Bug

1. Have car with livery options
2. Park it with no livery
3. Comes out with livery

### Expected Behavior

1. Have car with livery options
2. Park it with no livery
3. Comes out with no livery

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1f3yYb20NynSZC/d1337YCPyY5s?invite=cr-MSw0bnAsMTc2NTE5ODQs

**Comment by xXJamieXx** [comment] 2023-06-21 19:40
Duplicate of #1282

**Closed by xXJamieXx** 2023-06-21 19:40 UTC
Labels: type: Bug
