### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tbbubz** [ParadoxGamingRP/bugs-and-suggestions#2130] opened 2024-02-23 07:24 UTC
### Your Discord Name

tbbubz

### A clear and concise description of what the bug is

When prisoners check into infirmary at prison they get magically whisked away to pillbox which triggers a prison break alarm and when prisoners are sent back they lose all items that was on them.

### Steps to Reproduce the Bug

1. be sent to prison
2. check into infirmary
3. get yeeted to pillbox medical and trigger prison break alarm
4. get sent back to prison
5. lose all items left with the people at prison
6. 

### Expected Behavior

1. be sent to prison
2. check into infirmary
3. not get yeeted
4. continue sentence and not lose items

### Screenshots/Videos

i have none 

### Extra Notes (Optional)

i was the officer on duty when this happened unsure if it has been reported!

**Comment by Kromlec** [comment] 2024-02-23 07:26
Duplicate of #2115. Thank you for reporting. Unjailing and resending should stop them from losing their items.

**Closed by Kromlec** 2024-02-23 07:26 UTC
Labels: type: Bug
