### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jessithetransgal** [ParadoxGamingRP/bugs-and-suggestions#858] opened 2022-10-23 03:18 UTC
### Your Discord Name

🦋🌸Jessi le Transgirl fox✨#0663

### A clear and concise description of what the bug is

 Fishing crate allows me to put anything inside, I have no clue how or why this happened.

### Steps to Reproduce the Bug

I have no clue on what caused this to happen.

### Expected Behavior

Only allow fish into the crate

### Screenshots/Videos

![ezaw](https://user-images.githubusercontent.com/116474008/197371554-fa604b6a-66af-4522-a66b-e93edbebbfd2.jpg)

### Log File

I have no clue about the time, so heres all the logs from the day of buying the crate.

[CitizenFX_log_2022-10-17T215429.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845689/CitizenFX_log_2022-10-17T215429.log)
[CitizenFX_log_2022-10-17T215442.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845690/CitizenFX_log_2022-10-17T215442.log)
[CitizenFX_log_2022-10-17T223725.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845691/CitizenFX_log_2022-10-17T223725.log)
[CitizenFX_log_2022-10-17T223745.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845692/CitizenFX_log_2022-10-17T223745.log)
[CitizenFX_log_2022-10-17T224008.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845693/CitizenFX_log_2022-10-17T224008.log)
[CitizenFX_log_2022-10-17T025631.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845694/CitizenFX_log_2022-10-17T025631.log)
[CitizenFX_log_2022-10-17T154429.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845695/CitizenFX_log_2022-10-17T154429.log)
[CitizenFX_log_2022-10-17T154450.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845696/CitizenFX_log_2022-10-17T154450.log)
[CitizenFX_log_2022-10-17T182435.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845697/CitizenFX_log_2022-10-17T182435.log)
[CitizenFX_log_2022-10-17T182647.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845698/CitizenFX_log_2022-10-17T182647.log)
[CitizenFX_log_2022-10-17T215202.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9845699/CitizenFX_log_2022-10-17T215202.log)

**Comment by xXJamieXx** [comment] 2022-10-23 14:20
Duplicate of #816

**Closed by xXJamieXx** 2022-10-23 14:20 UTC
Labels: Bug
