### ISSUE TITLE
[BUG] Boat Dealership Doesn't open the Menu

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#782] opened 2022-09-20 01:12 UTC
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Third eyeing the Boats at the dealership, you can see the vehicle interaction and click on the option, but it doesn't open any meny from it.

### Steps to Reproduce the Bug

1. go to boat dealership
2. Left ALT on vehicle
3. Click on Vehicle Interaction

### Expected Behavior

Opens menu to switch vehicle.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/191145709-59dcdb56-0eff-4b97-8a82-c8fd761adb7d.png)

**Comment by xXJamieXx** [comment] 2022-09-23 21:48
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-09-23 21:48 UTC
Labels: Unable to Reproduce, Bug
