### ISSUE TITLE
PDX RACES NOT CANCELING IF MIN RACER REQUIREMENT IS MEET/ PDX RACES POP EVEN IF ONLY 1 IS IN QUEUE [BUG] 

### ISSUE THREAD

**Issue by HealedDegree** [ParadoxGamingRP/bugs-and-suggestions#1919] opened 2023-11-08 20:32 UTC
### Your Discord Name

HealedDegree

### A clear and concise description of what the bug is

When entering queue for races a PDX race will appear even if there are less than 5 racers in queue. For Ex if 2 is in queue the tablet will notify a race has appeared. Upon going to the start of the race if there is 4 racers or less the race will not cancel and will allow racers to compete. 

### Steps to Reproduce the Bug

1. join queue with 4 or less racers
2. wait for race to pop up 
3. go to start of race and join
4. race will start and not cancel 

### Expected Behavior

When entering the racing queue, if there are only 4 racers in the queue a race should not appear until 5 racers have joined. 
When entering the race at the start line, if the requirement of 5 racers hasnt been meet the race will be canceled. 

### Screenshots/Videos

![Screenshot 2023-11-08 152945](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119765213/11805efa-b0d4-47ea-bc06-9d42fac9f2ea)
![Screenshot 2023-11-08 151911](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119765213/5638c6f9-f78a-4cff-a14f-1ffcd4f10a61)

**Comment by xXJamieXx** [comment] 2023-11-08 21:02
Duplicate of #1918

**Closed by xXJamieXx** 2023-11-08 21:02 UTC
Labels: type: Bug
