### ISSUE TITLE
[BUG] <Chop shop not accepting car whilst car scrapping>

### ISSUE THREAD

**Issue by Nalyd24** [ParadoxGamingRP/bugs-and-suggestions#2142] opened 2024-02-28 21:56 UTC
### Your Discord Name

Nalyd24

### A clear and concise description of what the bug is

When trying to enter the chop shop the car is just being turned around and not accepting the car in the chop shop even though its the location you are sent to.

### Steps to Reproduce the Bug

1. Take the car
2. Go to the location provided
3. Try to enter Chop shop
4. Not get into chop shop

### Expected Behavior

Enter chop shop and continue with car scrapping

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1Y3WIF-k4d-1Q-/d1337fAUr8EZ?invite=cr-MSwwMlksNjExOTUyNzUs

**Comment by xXJamieXx** [comment] 2024-02-29 03:55
Duplicate of #2136

**Closed by xXJamieXx** 2024-02-29 03:55 UTC
Labels: type: Bug
