### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BlazinNut** [ParadoxGamingRP/bugs-and-suggestions#1362] opened 2023-04-17 00:36 UTC
### Your Discord Name

Blazin Nut#1776

### A clear and concise description of what the bug is

Liveries stick to cars forever

### Steps to Reproduce the Bug

1. Put any livery on your car
2. That livery will be on your car forever even if you change it in benny's and put it in garage it will revert back

### Expected Behavior

The livery would change to what i want it to be

### Screenshots/Videos

nah

**Comment by ithegreatgatsby** [comment] 2023-04-17 00:37
duplicate of #1282

**Closed by ithegreatgatsby** 2023-04-17 00:37 UTC
Labels: type: Bug
