### ISSUE TITLE
[BUG] Watering can breaking

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1409] opened 2023-05-06 22:01 UTC
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

When you use your watering can and it goes empty it breaks, you are not able to refill it. This is happening with both the older watering cans you've had for awhile and the new ones you buy. 

### Steps to Reproduce the Bug

1. Use watering can
2. watering can goes empty
3. Try to refill the watering can
4. watering can doesn't refill
5. gives error message "watering can durability is depleted"

### Expected Behavior

For the watering can to refill when you go to the water to refill it. 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1049113517749456998/1104527450194575480/image.png

https://cdn.discordapp.com/attachments/1049113517749456998/1104527514757513267/image.png

https://cdn.discordapp.com/attachments/1049113517749456998/1104527549045940284/image.png

**Comment by xXJamieXx** [comment] 2023-05-06 22:05
Duplicate of #1406

**Closed** 2023-05-06 22:05 UTC
Labels: type: Bug
