### ISSUE TITLE
[BUG] Chop delivery guy missing

### ISSUE THREAD

**Issue by saberontop** [ParadoxGamingRP/bugs-and-suggestions#1697] opened 2023-08-07 23:54 UTC
### Your Discord Name

fwsaber

### A clear and concise description of what the bug is

you get a car chopping car, get the text, go to the location and the guy isnt there

### Steps to Reproduce the Bug

idk the steps, may be random?

### Expected Behavior

guy will literally just not be there

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/124313620/79fc6516-a63c-437b-bb50-7f4e105b21a9

**Comment by xXJamieXx** [comment] 2023-08-24 15:08
Duplicate of #1641

**Closed by xXJamieXx** 2023-08-24 15:08 UTC
Labels: type: Bug

**Comment by HealedDegree** [comment] 2023-09-18 14:55
[CitizenFX_log_2023-09-18T144543.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12649432/CitizenFX_log_2023-09-18T144543.log)
![messages](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119765213/f04ce886-ea11-4bcf-8fad-adc154c996aa)

Texts messages from the job guy do not load so i was not able to find the drop off
