### ISSUE TITLE
[BUG] - MDT

### ISSUE THREAD

**Issue by CaptainJCaesar** [ParadoxGamingRP/bugs-and-suggestions#883] opened 2022-11-01 21:05 UTC
### Your Discord Name

CaptainJCaesar#2036

### A clear and concise description of what the bug is

The MDT kept closing and issues with name selection on Arrest/citation report. The MDT kept closing every time I attempted to open it for a select few moments till it finally stopped. It finally stopped and never closed out again(I was just sitting in my car). The MDT also was not letting me select a name when adding a criminal onto the Arrest/Citation report. Every time you pressed the +, and moved your mouse at all it closed out quickly. I’ve attempted this multiple different times and it still proceeded.

### Steps to Reproduce the Bug

1. Open up your MDT
2. Make a new Arrest/citation report
3. Attempt to add a criminal to the report
4. Move your mouse and it’ll close out on 

### Expected Behavior

When adding a name to your report, it’ll close the option out when pressing a name 

### Screenshots/Videos

N/A - Sorry, I originally wasn’t going to make a report and not in city.

**Comment by xXJamieXx** [comment] 2022-11-03 20:34
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-11-03 20:34 UTC
Labels: Unable to Reproduce, Scripting, Bug
