### ISSUE TITLE
[BUG] 678

### ISSUE THREAD

**Issue by thelord69** [ParadoxGamingRP/bugs-and-suggestions#680] opened 2022-08-24 00:59 UTC
### Your Discord Name

the_lord

### A clear and concise description of what the bug is

when diving there are only two or three corals to collect, after collecting those the diving spot still says active.

### Steps to Reproduce the Bug

diving

### Expected Behavior

many corals to collect and diving spot turns inactive and moves to a different spot on the map

### Screenshots/Videos

#678
![20220823205633_1](https://user-images.githubusercontent.com/111935516/186293476-6ae80645-df18-4dd3-87f2-27ff3040e001.jpg)

**Comment by xXJamieXx** [comment] 2022-08-27 15:49
Duplicate of #678

**Closed by xXJamieXx** 2022-08-27 15:49 UTC
