### ISSUE TITLE
[BUG] Neon

### ISSUE THREAD

**Issue by JHAWKS73** [ParadoxGamingRP/bugs-and-suggestions#2164] opened 2024-03-05 04:43 UTC
### Your Discord Name

jhawks73.

### A clear and concise description of what the bug is

My Neon under glow disappeared on me after i turned it off by thinking Neon and getting out of the car and it wont come back at all i have to repurchase it

### Steps to Reproduce the Bug

1. think neon and enter a stash house or park your car

### Expected Behavior

my neon shouldn't disappear when i turn them off

### Screenshots/Videos

don't have one

**Comment by Kromlec** [comment] 2024-03-05 04:45
Duplicate of #2161

**Closed by Kromlec** 2024-03-05 04:45 UTC
Labels: type: Bug
