### ISSUE TITLE
[BUG] Mines not letting you cut gems

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#1727] opened 2023-08-18 19:31 UTC
### Your Discord Name

NickNubbz

### A clear and concise description of what the bug is

when trying to cut gems at the mines it says "you dont have proper tools" i try to put steel bits on the dremmel and it doesnt work. buying a new dremmel works but gets costly as it only gives you 5 cuts.

### Steps to Reproduce the Bug

go to the mines
try to cut gem with dremmel you already have

### Expected Behavior

lets you cut gems and/or put steel bit on

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/74627555/23230a1f-0965-4b30-9375-f5f4ac6671ff)

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/74627555/c17cb6d1-3a52-4675-bcc4-807fc2762621)

### Extra Notes (Optional)

It wouldnt let me upload my video so i just took 2 screenshots with the error message and that i have the right stuff and it should work.

**Comment by Bac0nRamen** [comment] 2023-08-20 17:45
duplicate of #1724

**Closed by Bac0nRamen** 2023-08-20 17:45 UTC
Labels: type: Bug
