### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NaiveWoody** [ParadoxGamingRP/bugs-and-suggestions#653] opened 2022-08-13 08:53 UTC
### Your Discord Name

NaiveWoody

### A clear and concise description of what the bug is

When I pull my phone out, everything stops working, I tried resetting my screen to see if it was still responsive and my mouse was able to move and I could switch windows.  had to F8 quit and rejoin.

### Steps to Reproduce the Bug

Pull phone out.

### Expected Behavior

Everything stops working

### Screenshots/Videos

None taken

**Comment by xXJamieXx** [comment] 2022-08-13 09:14
Duplicate of #652

**Closed** 2022-08-13 09:15 UTC
