### ISSUE TITLE
MY GARAGE EAT ALL MY CARS HHHHHEEEEELLLLLPPPPP :(

### ISSUE THREAD

**Issue by Jacob017483** [ParadoxGamingRP/bugs-and-suggestions#2482] opened 2024-06-26 23:34 UTC
### Your Discord Name

james ram

### A clear and concise description of what the bug is

when i bought a garage i put all my cars in that garage will the next day i find all my cars are missing my app shows they are still parked in there but i cant see them and all my parking spots show that i have nothing assigned to them. i try to move my slots i parked my car and they show the assigned car in the f1 menu but not my car in the garage

### Steps to Reproduce the Bug

1. park a car in the large garage 
2. wait till restart
3. fly back in and check you garage the cars should be missing 

### Expected Behavior

you car will be in you garage when you come back from restart and you dont have to move parking spots every time you want to use your car

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/ee936d8e-3c19-4aed-857e-3505f29f5218

### Extra Notes (Optional)

if you would like a video just dm me on discord

### Log File

i will keep updating this over time 

DATES THAT ISSUE OCCURRED
6/25/24
6/26/24
6/27/24

**Comment by Jacob017483** [comment] 2024-06-26 23:41
![Screenshot 2024-06-26 194025](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/5e21e25e-4fd4-41fa-b701-88594f9622dc)
![Screenshot 2024-06-26 194038](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/d29cac30-4da4-4750-af17-3b6a9e2d6ead)

**Comment by Jacob017483** [comment] 2024-06-27 00:19
Uploading Untitled video - Made with Clipchamp (6).mp4…

**Comment by Jacob017483** [comment] 2024-06-27 00:20
https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/14626755-5fe7-4ed6-9dde-c235dafc1d10

**Comment by Jacob017483** [comment] 2024-06-28 02:30
no this was just funny

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/77c10e76-28e3-4efe-904d-72428f9428d9

**Comment by Jacob017483** [comment] 2024-06-28 02:56
> now this was just funny
> 
>  Untitled.video.-.Made.with.Clipchamp.7.mp4

[CitizenFX_log_2024-06-28T025235.log](https://github.com/user-attachments/files/16023624/CitizenFX_log_2024-06-28T025235.log)

**Comment by SaraLef** [comment] 2024-07-02 21:29
Can confirm this happened to mine as well, where you have to replace all the spots. If you have cars in there you also need to put a spot where the car used to be for it to spawn back.

**Comment by emeraldleo1982** [comment] 2024-07-02 21:32
> Can confirm this happened to mine as well, where you have to replace all the spots. If you have cars in there you also need to put a spot where the car used to be for it to spawn back.

Sometimes that doesn't work either and you have to kick the car out to the public vehicle depot, or wait until storm for it to come back.

**Comment by xXJamieXx** [comment] 2024-07-03 10:54
Duplicate of #2390

**Closed by xXJamieXx** 2024-07-03 10:54 UTC
Labels: type: Bug
