### ISSUE TITLE
ENGINE SWAP BUG, Engine swap is not performing as it use too on my Flash GT.

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#1453] opened 2023-05-29 23:15 UTC
### Your Discord Name

ZOIMBIE#5888

### A clear and concise description of what the bug is

My flash gt sports car has an engine swap in it. Before all the new update's with the pd cars it was working just fine and as intended. Now ever since the update my engine swap flash gt will not go over 118. it is 100% repaired and it just seems to red line and not go over 118 what so ever.

### Steps to Reproduce the Bug

you will need an engine swapped Flash GT and you will need to go down the highway using nos and it will not go over 118.

### Expected Behavior

The car will just red line and not go over 118.

### Screenshots/Videos

if videos are needed please contact me thanks.

### Extra Notes (Optional)

if you want videos and photos just let me know thanks.

**Comment by xaroht** [comment] 2023-05-30 02:02
Me and Tweeko both noticed this on the R35.

I have the RB26 
Tweeko has the K20 (not sure if that info helps) 

The R35 redlines in 5th Gear instead of going through to 6th

Doesn't go above 125mph without bumps but gets completely gapped by non swapped cars.

**Comment by ZOIMBIE3** [comment] 2023-05-30 23:08
I have the subaru swap in my flash gt and yea just red lines at 118

**Comment by JnKTechstuff** [comment] 2023-05-31 02:24
Every day I wonder why the people at the tuner shop don't follow instructions.

**Comment by xXJamieXx** [comment] 2023-06-04 22:44
Duplicate of #1351

**Closed by xXJamieXx** 2023-06-04 22:44 UTC
Labels: type: Bug
