### ISSUE TITLE
[BUG] Slurptruck doesnt always give keys

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2455] opened 2024-06-23 22:02 UTC
### Your Discord Name

ssara

### A clear and concise description of what the bug is

When taking the truck out you sometimes get the truck but no key

### Steps to Reproduce the Bug

Pull out truck
Don't get keys.
Lockpick truck

### Expected Behavior

Pull out truck
Get keys

### Screenshots/Videos

N/A

**Comment by Bac0nRamen** [comment] 2024-06-24 16:22
Duplicate of #2433

**Closed by Bac0nRamen** 2024-06-24 16:21 UTC
Labels: type: Bug
