### ISSUE TITLE
[BUG] Unable to sell vehicle "don't have paperwork"

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#563] opened 2022-07-15 05:31 UTC
### Your Discord Name

Forgotten#0031

### A clear and concise description of what the bug is

unable to sell cars
when you go to check price or sell it tells you that you don't have the paperwork
note I did put the car back in my garage then try to sell it a gain to the same result and I tried mutable vehicles 

### Steps to Reproduce the Bug

1. pull car out of garage
2. drive to sell point
3.  try to check price / sell car via f1

### Expected Behavior

should sell the car or tell me the price i can sell it for

### Screenshots/Videos

https://www.youtube.com/watch?v=3ZJgvHO_91s
https://user-images.githubusercontent.com/85376462/179156239-a4a9f948-9363-4638-80a4-0bbab94c6b15.mp4

### Log File

[CitizenFX_log_2022-07-15T052545.log](https://github.com/xXJamieXx/paradox-bugs/files/9118103/CitizenFX_log_2022-07-15T052545.log)

**Comment by xXJamieXx** [comment] 2022-07-19 11:38
> [CitizenFX_log_2022-07-19T100136.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9140224/CitizenFX_log_2022-07-19T100136.log)
> 
> Bought a car of someone, money took. The car appears in my insurance app and I can park it in my home garage. When taking it out the garage I do not get keys and when taking it to the car buyer I do not have the paperwork

Can you share your steam name so I can check some things?

**Comment by WeeRio26** [comment] 2022-07-19 13:11
Steam name: Rio_P06 👍

**Comment by WeeRio26** [comment] 2022-07-19 15:59
C DAWWG

**Comment by xXJamieXx** [comment] 2022-07-19 22:55
@unforgiven8233 @WeeRio26 I believe I may have found the issue and resolved it. Could you please try again and confirm if the issue is resolved? :)

**Comment by WeeRio26** [comment] 2022-07-20 10:27
thats it fixed now, thank you

**Closed** 2022-07-20 11:04 UTC
Labels: Confirmed, Scripting
