### ISSUE TITLE
[BUG] Chop location turn in broken

### ISSUE THREAD

**Issue by shleeyy** [ParadoxGamingRP/bugs-and-suggestions#2139] opened 2024-02-28 06:42 UTC
### Your Discord Name

freckles4

### A clear and concise description of what the bug is

Gained access of vehicle, received location once arriving to destination had the option to enter.. nothing happened upon hitting my E.

### Steps to Reproduce the Bug

1. Get Chop Email
2. Find Car
3. Drive Car to location
4. Drive to 162 to drop off car
5. Flex E cut to teleport but position of car changes and that's it,

### Expected Behavior

turn in car to location and have something happen. not sure what is supposed to happen but i still had the car and no parts in return...

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1XXMWg557QfgtD/d1337xUQSRrz?invite=cr-MSx6aU8sMTg5NzA2MzQwLA

**Comment by xXJamieXx** [comment] 2024-02-28 21:42
Duplicate of #2136

**Closed by xXJamieXx** 2024-02-28 21:42 UTC
Labels: team: Scripting, type: Bug
