### ISSUE TITLE
[BUG] hunting at 2005 sends you into the sky

### ISSUE THREAD

**Issue by Waldo-afriki** [ParadoxGamingRP/bugs-and-suggestions#714] opened 2022-08-31 14:37 UTC
### Your Discord Name

pacfist-larx#5651

### A clear and concise description of what the bug is

While hunting on the hill at 2005, after skinning a boar i immediately started to run forward into the boar in order to quickly get to where i was palcing the bait directly behind the animal on the top part of the same hill. when i ran into the dissapearing carcass i got ejected about 30feet up in the air and fell into an incapacitated state. 

### Steps to Reproduce the Bug

1. place bait on top of hill at 2005
2. shoot the boar in the face on the side of the hill not at the top
3. skin the animal
4. as soon as the skinning is complete before the animal dissapears run into it
5. join mile high club 

### Expected Behavior

as soon as you run into the dead boar you should be ejected in the air. 

### Screenshots/Videos

sadly i do not have video of this event as i dont ususally record hunting. and ever sine the new phones came out record what happened on fivem my windows gaming does not recognise it as a game

### Extra Notes (Optional)

idk it might be a one time thing, I haven't tried recreating it but at least ya know it can happen. 

### Log File

[Uploading CitizenFX_log_2022-08-31T131032.log…]()

**Comment by xXJamieXx** [comment] 2022-09-11 21:49
Unable to reproduce this issue and will therefore be closing it.

**Closed by xXJamieXx** 2022-09-11 21:49 UTC
Labels: Unable to Reproduce, Scripting, Bug
