### ISSUE TITLE
[BUG]   Smelter takes material but doesn't  give finished product 

### ISSUE THREAD

**Issue by Weredwarfed** [ParadoxGamingRP/bugs-and-suggestions#1112] opened 2023-01-30 23:44 UTC
### Your Discord Name

Weredwarfed

### A clear and concise description of what the bug is

 When you smoke any of the materials down in the mind they do not actually give you back the finish product,  At first I thought it was just me but I had somebody else come and try and they have the same issue.  I tried it with one of each of the different ore types it's doing it with all of them

### Steps to Reproduce the Bug

Start smelting me ore
 After it goes through the smelting process you do not get resources back and lose what you put in

### Expected Behavior

 Expect to not get anything back when you try to you smelt

### Screenshots/Videos

 I don't have any Cam I'm sorry

**Comment by xXJamieXx** [comment] 2023-02-01 15:01
Duplicate of #1111

**Closed by xXJamieXx** 2023-02-01 15:01 UTC
Labels: Bug
