### ISSUE TITLE
[BUG] Diving no longer working alteast since yesterday

### ISSUE THREAD

**Issue by vyberyt** [ParadoxGamingRP/bugs-and-suggestions#711] opened 2022-08-30 20:58 UTC
### Your Discord Name

VyberYT#7147

### A clear and concise description of what the bug is

Diving isnt working properly, try to 3rd eye it and click collect coral on it and it does nothing. Didn't even see the usual question marks

### Steps to Reproduce the Bug

Go dive
Try to collect coral

### Expected Behavior

To collect coral

### Screenshots/Videos

![Diving](https://user-images.githubusercontent.com/111221191/187541317-4f8c0906-9b68-4cf2-9c25-c1bc9fc528fc.png)
![Screenshot_20](https://user-images.githubusercontent.com/111221191/187541326-d9816d7d-5f16-4066-bf6d-1131860d3273.png)

### Log File

[CitizenFX_log_2022-08-30T203951.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9456600/CitizenFX_log_2022-08-30T203951.log)

**Comment by xXJamieXx** [comment] 2022-08-30 20:59
Duplicate of #706

**Closed by xXJamieXx** 2022-08-30 20:59 UTC
