### ISSUE TITLE
[BUG] manor interior

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#631] opened 2022-08-04 20:15 UTC
### Your Discord Name

mac_ceo#7021 Riley Johnson

### A clear and concise description of what the bug is

the manor interior need a fix very fast seeing through the floor only seeing props in first person ect

### Steps to Reproduce the Bug

n/a

### Expected Behavior

props be able to see not just in first person not being able to sse through floor ect

### Screenshots/Videos

https://medal.tv/games/requested/clips/vgXqcRJASdtuH/d1337gfesEap?invite=cr-MSxxUlksNjIwNTkzNzQs

### Log File

[CitizenFX_log_2022-08-04T201030.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9263006/CitizenFX_log_2022-08-04T201030.log)

**Comment by xXJamieXx** [comment] 2022-08-05 15:21
Duplicate of #608

**Closed by xXJamieXx** 2022-08-05 15:21 UTC
