### ISSUE TITLE
[BUG] <Corals giving less than stated and the location does not pop up when turning on scanner>

### ISSUE THREAD

**Issue by quixzyXD** [ParadoxGamingRP/bugs-and-suggestions#2047] opened 2024-01-09 22:45 UTC
### Your Discord Name

captainbrob

### A clear and concise description of what the bug is

when i try to do corals the location doesnt pop up and I keep getting barley any money for it :(

### Steps to Reproduce the Bug

fix corals waypoint when activating scanner

### Expected Behavior

get payed more and put waypoint

### Screenshots/Videos

.

### Extra Notes (Optional)

.

**Comment by Darahz** [comment] 2024-01-10 17:51
Did a fix to prevent this (dupe of #2038 )

**Closed by Darahz** 2024-01-10 17:51 UTC
Labels: type: Bug
