### ISSUE TITLE
[BUG] House Flickering

### ISSUE THREAD

**Issue by H0lyPika** [ParadoxGamingRP/bugs-and-suggestions#632] opened 2022-08-04 20:22 UTC
### Your Discord Name

HolyPika#9815

### A clear and concise description of what the bug is

So whenever you go up the stairs in the Lupine Manor there is alot of Flickering of Persons and Items

### Steps to Reproduce the Bug

stand on the second to last step before the top and you will start flickering and just running around on the second floor you still can cause the flickering to happen

### Expected Behavior

being able to walk up stairs to the top floor and not flickering out of existence with the Items placed inside of the house

### Screenshots/Videos

[Flickering when upstairs](https://youtu.be/qv2F3DXU3UQ)

### Log File

[CitizenFX_log_2022-08-04T201834.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9263078/CitizenFX_log_2022-08-04T201834.log)

**Comment by xXJamieXx** [comment] 2022-08-05 15:22
Duplicate of #608

**Closed by xXJamieXx** 2022-08-05 15:22 UTC
