### ISSUE TITLE
[ENHANCEMENT] Ability to see transactions of business account

### ISSUE THREAD

**Issue by Strandis** [ParadoxGamingRP/bugs-and-suggestions#627] opened 2022-08-03 14:32 UTC
**Your Discord Name**
Axel

**Describe the annoyance**
An option for managers to see previous transactions (logs) in and out of the bank account. By this being able to track when and to where money is flowing. It is also a way to keep track of who is withdrawing/depositing receipts

**Comment by SpiceF0x** [comment] 2022-08-03 16:31
https://github.com/ParadoxGamingRP/bugs-and-suggestions/issues/577 😉

**Comment by Strandis** [comment] 2022-08-03 16:40
I forgot to look

**Comment by xXJamieXx** [comment] 2022-08-04 09:19
Duplicate of #577

**Closed by xXJamieXx** 2022-08-04 09:19 UTC
Labels: Enhancement
