### ISSUE TITLE
[BUG] Pry open bunk still overlapping the cleaning bunk option

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#959] opened 2022-12-02 13:02 UTC
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

Whenever I try to clean a bunk for a prison job it overlaps it

### Steps to Reproduce the Bug

1. Start Cell Block Prison Job.
2. Go to clean bunk
3. Pry Open Bunk overlapped

### Expected Behavior

Be able to clean bunk without it overlapping

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/81855046/205298910-98e8b365-20bd-45ce-a20d-d3561217dd9c.png)

**Comment by xXJamieXx** [comment] 2022-12-02 13:27
Duplicate of #830

**Closed** 2022-12-02 13:27 UTC
Labels: Bug
