### ISSUE TITLE
[BUG] Water in my interior

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1935] opened 2023-11-16 05:18 UTC
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

So when purchasing a garage interior, there is  water in the back left hand side of the interior that you can swim in and i can't decorate appropriately. 

### Steps to Reproduce the Bug

1 . buy interior
2. swim

### Expected Behavior

you will become a fish

### Screenshots/Videos

https://youtu.be/B1aAMqhALLM

### Extra Notes (Optional)

Please excuse the audio on my clip, my mic is fucked and im sick lol

### Log File

[leak in garage.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13372608/leak.in.garage.txt)

**Comment by xXJamieXx** [comment] 2023-11-26 18:46
Duplicate of #1895

**Closed by xXJamieXx** 2023-11-26 18:46 UTC
Labels: type: Bug
