### ISSUE TITLE
[BUG] Pounder Custom Trunk

### ISSUE THREAD

**Issue by Ashleyfur** [ParadoxGamingRP/bugs-and-suggestions#1119] opened 2023-02-01 04:23 UTC
### Your Discord Name

Ashleyfur#0001

### A clear and concise description of what the bug is

I've tested the Mule vs the Pounder Custom trunks. The Mule works however the Pounder Custom is still inaccessible. Its glove box does work. I've walked around the entirety of the vehicle as well as inside the storage bay and on top of it as seen by the video attached. However, nothing worked to open it. 

### Steps to Reproduce the Bug

1. Get a Pounder Custom.
2. Attempt to open trunk.
3. Trunk does not open. 

### Expected Behavior

Trunk to open and be able to place items within. 

### Screenshots/Videos

https://ufile.io/se9iq54p

### Extra Notes (Optional)

#1042 Same issue was stated in this bug report. 

### Log File

[CitizenFX_log_2023-02-01T034857.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10553229/CitizenFX_log_2023-02-01T034857.log)

**Comment by xXJamieXx** [comment] 2023-02-01 08:36
Duplicate of #1109

**Closed** 2023-02-01 08:36 UTC
Labels: Bug
