### ISSUE TITLE
[BUG] Dispatch - Gunshots

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#595] opened 2022-07-23 03:38 UTC
### Your Discord Name

BDZ#0001

### A clear and concise description of what the bug is

Only a few calls show up as shots fired. Been getting a lot of hunting shots fired calls but not shots fired related to scenes that PD should be aware of.

### Steps to Reproduce the Bug

N/A

### Expected Behavior

Fire a few round - Dispatch alerts to an active 10-13

### Screenshots/Videos

n/a

**Comment by Sly-Panda** [comment] 2022-07-25 11:52
Shots fired calls don't have a 100% chance to trigger and whether or not they trigger depends on multiple variables.  Having tested it appears to be working as intended.

**Comment by BrotherDayZ** [comment] 2022-07-25 20:17
Can you test this with class 2's? On the day of reporting this I know there was an active war between 2 gangs and not a single dispatch was issued during multiple fights between them

**Comment by Sly-Panda** [comment] 2022-07-25 21:17
Where did the gunfight take place?

**Comment by BrotherDayZ** [comment] 2022-07-25 21:34
Sandy for the most part. At Open Road and some behind Bolingbrooke pen

**Comment by xXJamieXx** [comment] 2022-08-20 21:28
Without going into detail about how the system works, I will be closing this under the impression that the system is working as intended and what you experienced is correct with how the system is currently set up and therefore not a bug.

**Closed by xXJamieXx** 2022-08-20 21:28 UTC
Labels: Scripting
