### ISSUE TITLE
[BUG] Hurt

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2405] opened 2024-06-16 20:59 UTC
### Your Discord Name

ssara

### A clear and concise description of what the bug is

The bleeding effect pops up when changing oufits at kildares.

### Steps to Reproduce the Bug

Change at Kildares
Start to bleed

### Expected Behavior

Change at kildares
Work as normal

### Screenshots/Videos

N/A

**Comment by tusktheshrew** [comment] 2024-06-16 21:27
this also happens sometimes for the people changing at the Tuning Shop.

**Comment by natashajoan** [comment] 2024-06-16 22:17
Also happens at G&G.

**Comment by BBstud44** [comment] 2024-06-17 06:00
Also happens at our HQ. It seems to be an everywhere issue

**Comment by xXJamieXx** [comment] 2024-07-13 16:17
Duplicate of #2296

**Closed by xXJamieXx** 2024-07-13 16:17 UTC
Labels: team: Scripting, type: Bug
