### ISSUE TITLE
[BUG] Elevator in pillbox not working

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#780] opened 2022-09-19 22:18 UTC
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Elevator in the back isnt working. Cannot thirdeye it

### Steps to Reproduce the Bug

Try to thirdeye the button
Nothing

### Expected Behavior

Be able to go down to the ambo

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment] 2022-09-23 21:46
Duplicate of #764

**Closed by xXJamieXx** 2022-09-23 21:46 UTC
Labels: Unable to Reproduce, Bug
