### ISSUE TITLE
[BUG] I'm not blue 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1454] opened 2023-05-30 09:06 UTC
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Apply ice packs or vests or whatever, fly out, fly in, it be gone. 

### Steps to Reproduce the Bug

Apply ice pack
Fly out
Fly in
Gone

### Expected Behavior

Apply ice pack
Fly out
Fly in 
It would be the same amount of blue as when you first flied out.

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment] 2023-06-04 22:47
Duplicate of #1367

**Closed by xXJamieXx** 2023-06-04 22:47 UTC
Labels: type: Bug
