### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mambaa19** [ParadoxGamingRP/bugs-and-suggestions#2376] opened 2024-06-10 16:14 UTC
### Your Discord Name

Mambaa_19

### A clear and concise description of what the bug is

I got a manual transmission installed in my car the other day and since before the last restart by can has been automatic, it still says it's a manual and shifts but is pointless as it acts as if its automatic.

### Steps to Reproduce the Bug

Hop in car, abd it not be manual as is supposed to be

### Expected Behavior

Get in vehicle and have to drive vehicle, shifting through gears manually.

### Screenshots/Videos

n/a

**Comment by xXJamieXx** [comment] 2024-06-10 20:12
Duplicate of #2370

**Closed by xXJamieXx** 2024-06-10 20:12 UTC
Labels: type: Bug
