### ISSUE TITLE
[BUG] Bee Hive & house disappearing 

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#2291] opened 2024-05-31 22:42 UTC
### Your Discord Name

BBstud27

### A clear and concise description of what the bug is

I placed down a Bee Hive & house and left them for a little bit came back and the were both gone

### Steps to Reproduce the Bug

1. Place Hive and House
2. put queen and worker bee's in Hive
3. leave said house and hive 
4. come back to said house and hive
5. be sad that your beautiful bee's have been engulfed by the void

### Expected Behavior

for my house and hive to still be there if i need to leave the area

### Screenshots/Videos

N/A

### Extra Notes (Optional)

The logs i posted were a little while after the incident so they wont be at the end if you need to use them

### Log File

[Bee Hive & House.txt](https://github.com/user-attachments/files/15519264/Bee.Hive.House.txt)

**Comment by BBstud44** [comment] 2024-06-01 06:38
its possible it got sent under the map because now that there are blips turned on i can see the blips where i placed the hive and house but they arent here

**Comment by Nicklmfao** [comment] 2024-06-01 17:18
They disappeared for me as well as of today, they were fine yesterday when I flew out.

**Comment by xXJamieXx** [comment] 2024-06-04 16:21
Duplicate of #2282

**Closed** 2024-06-04 16:21 UTC
Labels: team: Scripting, type: Bug, state: Duplicate
