### ISSUE TITLE
[BUG] <unable to change license plate on car>

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2023] opened 2023-12-26 17:52 UTC
### Your Discord Name

KevStax 

### A clear and concise description of what the bug is

no option in the mod shop to change car license plates.

### Steps to Reproduce the Bug

1. go in mod shop
2. look for plate # change
3. no option found

### Expected Behavior

1. go in mod shop
2. change license plate # 
3.  be happy

### Screenshots/Videos

n/a

**Comment by xXJamieXx** [comment] 2024-01-04 18:46
Duplicate of #2001

**Closed by xXJamieXx** 2024-01-04 18:46 UTC
Labels: type: Bug
