### ISSUE TITLE
[BUG] Illegal Selling Issues

### ISSUE THREAD

**Issue by Charby99** [ParadoxGamingRP/bugs-and-suggestions#918] opened 2022-11-15 05:01 UTC
### Your Discord Name

Charby99

### A clear and concise description of what the bug is

I am unable to sell weed to any locals. I have tried multiple times at multiple locations. I have sold tens of thousands of dollars in weed before and after the Tsunami today it would not work for me or any of my crew mates. 

### Steps to Reproduce the Bug

Acquire bag of weed
Find a group of locals
Flex F1 and click on Self Actions
Click on "corner selling" and try to sell bags of weed to locals using third eye when they approach you
Locals are not approaching me to buy weed bags

### Expected Behavior

Locals should approach player and stand by player until interacted with through third eye

### Screenshots/Videos

I have Videos unable to upload them because file is too big. If needed my discord is Charby99#0124 i can send there

### Log File

[CitizenFX_log_2022-11-15T010743.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10009279/CitizenFX_log_2022-11-15T010743.log)

**Comment by xXJamieXx** [comment] 2022-11-15 15:34
Duplicate of #916

**Closed by xXJamieXx** 2022-11-15 15:34 UTC
Labels: Bug
