### ISSUE TITLE
[BUG] Not receiving payment for two people garbage route

### ISSUE THREAD

**Issue by oopsemilyy** [ParadoxGamingRP/bugs-and-suggestions#683] opened 2022-08-24 19:52 UTC
### Your Discord Name

yoitsem#2449

### A clear and concise description of what the bug is

Not receiving payment from garbage job with another person. After third-eyeing the guy at the garbage depot and selecting "Collect Payslip" I get a message saying "The person who started the route is required to collect pay!" when I'm the one who started the route. The other person on the route also tried, and received the same message.

### Steps to Reproduce the Bug

1. Start a garbage route
2. Have another person get in the truck
3. Complete the all the garbage stops together
4. Take the truck back to the depot
5. Have the person who started the route attempt to receive payslip

### Expected Behavior

I expected us to be able to complete the entire garbage route, come back to the depot, and be able to receive our money for the job we completed.

### Screenshots/Videos

![20220824154305_1](https://user-images.githubusercontent.com/112020720/186509761-abe4e9f8-fc1a-4a1c-b9a1-439ad0570545.jpg)

### Log File

[CitizenFX_log_2022-08-24T180505.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9419020/CitizenFX_log_2022-08-24T180505.log)

**Comment by xXJamieXx** [comment] 2022-08-27 15:50
Duplicate of #679

**Closed by xXJamieXx** 2022-08-27 15:50 UTC
